### ISSUE TITLE
Stuck on config

### ISSUE THREAD

**Issue by deMathias** [waw-eve/seat-mumble-register#2]
Hello, first of all thank you for adding a mumble plugin. Teamspeak very costly.

I have added plugin to seat (=ok)
![image](https://user-images.githubusercontent.com/47175867/131857446-ab1938f9-ae43-4b7d-86d5-2c0863ffaa21.png)

I have docker running (=ok)
![image](https://user-images.githubusercontent.com/47175867/131857519-82a59082-9520-421c-b02a-b2deb5b2f41a.png)
port 81 because 80 in use.

I set up ice on murmur and change config to have new encrypt key and ice password.

on seat i set up like this:

![image](https://user-images.githubusercontent.com/47175867/131857785-b15fccf7-44f5-48ac-a409-44a6e830aa87.png)

after trying to register i get error 500.

![image](https://user-images.githubusercontent.com/47175867/131857865-e70022e3-993a-4444-965a-117a468280e2.png)

What am I missing sir?

if you want to chat my discord is `Opolusia#0093`

**Comment by KagurazakaNyaa** [comment]
Can you try to use an external IP address for the Agent URL instead of 127.0.0.1? 
Or if the agent and SeAT are in the same docker network, you can try to use the container name to access the agent.

**Comment by KagurazakaNyaa** [comment]
I just configured it in the local cluster, and the problem can be reproduced when the URL is configured as 127.0.0.1. I tried the following configuration and it worked very well.

docker-compose.yml
```yaml
version: "3.3"
services:
  server:
    image: sudoforge/mumble-server
    restart: unless-stopped
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
      - "6502:6502/tcp"
    environment:
      #- MUMBLE_SERVERPASSWORD=
      - MUMBLE_ENABLESSL=0
      - MUMBLE_ICE=tcp -h 0.0.0.0 -p 6502
      - MUMBLE_ICESECRETREAD=testtesttest
      - MUMBLE_ICESECRETWRITE=testtesttest
      - MUMBLE_IMAGEMESSAGELENGTH=0
      - MUMBLE_SENDVERSION=true
      - MUMBLE_DEFAULTCHANNEL=1
      - MUMBLE_SUGGESTPOSITIONAL=true
      - MUMBLE_SUGGESTPUSHTOTALK=true
      - MUMBLE_SUGGESTVERSION=1.3.0
      - SUPERUSER_PASSWORD=testtesttest
    volumes:
      - ./data/mumble:/data

  agent:
    image: alliancewaw/seat-mumble-register
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - 81:80/tcp
    volumes:
      - ./data/agent:/app/data
```

data/agent/config.json
```json
{
  "encryptKey": "testtesttest",
  "mumbleIceAddr": "tcp -h server -p 6502",
  "mumbleIceSecret": "testtesttest"
}
```
![image](https://user-images.githubusercontent.com/7751303/131937829-2a7eb9e0-6014-40d0-8740-2c1dab9aab4f.png)
