### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by pdgilmartin** [waw-eve/seat-mumble-register#3]
This is giving a 500 server error when you enter an email and try to register account

**Comment by KagurazakaNyaa** [comment]
I need more detailed error logs to know the problem
However, you can first check if you forgot to deploy https://github.com/waw-eve/seat-mumble-register-backend

**Comment by pdgilmartin** [comment]
I did as instructed:

Edit your .env file,locate the line SEAT_PLUGINS and append alliancewaw/seat-mumble-register at the end.

Then , run docker-compose up -d to take effect.

My SeAT is running on digital ocean and mumble is run through lightspeed

**Comment by thrasherht** [comment]
I can confirm, after setting up the seat plugin, as well the backend container.
I am get a 500 error when attempting to register a user.

Below is a stacktrace from the laravel logs on the seat web container.

`[2023-02-22 21:35:50] local.ERROR: Uninitialized string offset: -1 {"userId":47,"exception":"[object] (ErrorException(code: 0): Uninitialized string offset: -1 at /var/www/seat/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/SymmetricKey.php:2590)
[stacktrace]
#0 /var/www/seat/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/SymmetricKey.php(2590): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Uninitialized s...', '/var/www/seat/v...', 2590, Array)
#1 /var/www/seat/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/SymmetricKey.php(1659): phpseclib3\\Crypt\\Common\\SymmetricKey->unpad('')
#2 /var/www/seat/vendor/alliancewaw/seat-mumble-register/src/Http/Controllers/RegisterController.php(74): phpseclib3\\Crypt\\Common\\SymmetricKey->decrypt('')
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): WarAndWormhole\\Seat\\MumbleRegister\\Http\\Controllers\\RegisterController->update(Object(Illuminate\\Http\\Request))
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('update', Array)
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(WarAndWormhole\\Seat\\MumbleRegister\\Http\\Controllers\\RegisterController), 'update')
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'mumble.register')
#11 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Locale.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\\Web\\Http\\Middleware\\Locale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Authenticate.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\\Web\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/seat/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#46 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#47 /var/www/seat/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#48 {main}
`

**Comment by recursivetree** [comment]
Without debugging or being able to verify it, it seems like the seat part of the system doesn't get the response it wants from the backend. Check your Agent URL in the settings and make sure the backend is reachable from seat-web

**Comment by recursivetree** [comment]
Additionally, from reading the above, have you made sure that you deployed https://github.com/waw-eve/seat-mumble-register-backend on your docker stack? there hasn't been an answer

**Comment by thrasherht** [comment]
I did answer, it is the first line in my response.
I will paste my original response below
```
I can confirm, after setting up the seat plugin, as well the backend container.
I am get a 500 error when attempting to register a user.
```

I finally got it working, after moving the backend container to a whole other machine. It seems like whatever error I was having, was being caused by the systems inability to communicate with that backend container.
It seems like very bad error handling if it generates this type of end user message when it is unable to communicate. 

It would be much better if it checked the connection first, and provided a proper error message indication lack of connection.

**Comment by recursivetree** [comment]
Assuming you are using docker-compose, have you checked if they share a network? That's probably the most likely cause for them being unable to communicate.

I agree on the error handling, it is poor. Maybe write a PR for it and fix it?

**Comment by porowns** [comment]
@recursivetree 
```
version: "3.2"

services:

  mariadb:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - "mariadb-data:/var/lib/mysql"
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  redis:
    image: redis:5-alpine
    restart: always
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  traefik:
    image: traefik:2.2
    restart: always
    command:
      - --log.level=INFO
      - --api=true
      - --api.dashboard=${APP_DEBUG}
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      # ACME
      - --certificatesresolvers.primary.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.primary.acme.storage=acme.json
      - --certificatesresolvers.primary.acme.httpchallenge.entrypoint=web
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_HTTPS_PORT}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.api.rule=Host(`traefik.${TRAEFIK_DOMAIN}`)"
      #- "traefik.http.routers.api.service=api@internal"
      #- "traefik.http.routers.api.entrypoints=websecure"
      # Uncomment to enable HTTPS via ACME
      #- "traefik.http.routers.api.tls.certResolver=primary"
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-web:
    image: eveseat/seat:4
    restart: always
    command: web
    volumes:
      - ./packages:/var/www/seat/packages:ro  # development only
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seat-web.rule=Host(`${SEAT_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.seat-web.entrypoints=websecure"
      # Uncomment to enable HTTPS via ACME
      - "traefik.http.routers.seat-web.tls.certResolver=primary"
    depends_on:
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-worker:
    image: eveseat/seat:4
    restart: always
    command: worker
    volumes:
      - ./packages:/var/www/seat/packages:ro  # development only
    env_file:
      - .env
    depends_on:
      - seat-web # so that we can get db migrations done
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-cron:
    image: eveseat/seat:4
    restart: always
    command: cron
    volumes:
      - ./packages:/var/www/seat/packages:ro  # development only
    env_file:
      - .env
    depends_on:
      - seat-web # so that we can get db migrations done
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
  server:
    image: sudoforge/mumble-server
    restart: unless-stopped
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
      - "6502:6502/tcp"
    environment:
      #- MUMBLE_SERVERPASSWORD=
      - MUMBLE_ENABLESSL=0
      - MUMBLE_ICE=tcp -h 0.0.0.0 -p 6502
      - MUMBLE_ICESECRETREAD=xNvyqGYc6YzuQNUjU6xZBqq4PzqqN72U2y369rhq
      - MUMBLE_ICESECRETWRITE=xNvyqGYc6YzuQNUjU6xZBqq4PzqqN72U2y369rhq
      - MUMBLE_IMAGEMESSAGELENGTH=0
      - MUMBLE_SENDVERSION=true
      - MUMBLE_DEFAULTCHANNEL=1
      - MUMBLE_SUGGESTPOSITIONAL=true
      - MUMBLE_SUGGESTPUSHTOTALK=true
      - MUMBLE_SUGGESTVERSION=1.3.0
      - SUPERUSER_PASSWORD=xNvyqGYc6YzuQNUjU6xZBqq4PzqqN72U2y369rhq
    networks:
      - seat-network
    volumes:
      - ./data/mumble:/data

  agent:
    image: alliancewaw/seat-mumble-register
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - 81:80/tcp
    networks:
      - seat-network
    volumes:
      - ./data/agent:/app/data

volumes:
    mariadb-data:

networks:
    seat-network:
```

I'm running into the same issue. Everything is on the same network, in the same compose file.
